version: '2'
services:
    db:
        container_name: choros-cron-dev-db
        image: mysql
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    web:
        container_name: choros-cron-dev-web
        build:
            context: ../../
            dockerfile: docker/dev/web/Dockerfile
        ports:
            - "5500:80"
        environment:
            DATABASE_HOST: db
            DATABASE_PORT: 3306
            DATABASE_NAME: symfony
            DATABASE_USER: root
            DATABASE_PASSWORD: root
            APP_SECRET: ThisTokenIsNotSoSecretChangeIt
        volumes:
            - ../../symfony:/app/symfony
            - ../../src:/app/src
        links:
            - db
