services:
  choros.command_bus:
    class: 'Choros\Infrastructure\Application\CommandBus\ProophAdapter'
    arguments: ["@prooph.service_bus.command_bus"]

  choros.slug:
    class: 'Choros\Infrastructure\Application\Slug\SlugifyAdapter'
    arguments: ["@slugify"]

  slugify:
    class: 'Cocur\Slugify\Slugify'
