services:
  choros.command_bus:
    class: 'Choros\Infrastructure\Application\CommandBus\TacticianAdapter'
    arguments: ["@tactician.commandbus"]

  choros.slug:
    class: 'Choros\Infrastructure\Application\Slug\SlugifyAdapter'
    arguments: ["@slugify"]

  slugify:
    class: 'Cocur\Slugify\Slugify'
