imports:
    - { resource: config.yml }

framework:
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "php://stdout"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]

nelmio_api_doc: ~
